### ISSUE TITLE
cwl-runner validate fails after upgrade

### ISSUE THREAD

**Issue by BJWiley233** [common-workflow-language/cwl-upgrader#69]
The files are all existing and in correct folder structure after I moved them.  Now when I run `cwl-runner --validate` I get this error below and `org.w3id.cwl.cwl.File` is no where in this yml file.

```
Tool definition file:///Users/****/****/UKBB/analysis-workflows/definitions_v1.1/tools/vep.cwl failed validation:
definitions_v1.1/tools/vep.cwl:5:1:                       checking field `requirements`
...more lines
...more lines
definitions_v1.1/types/vep_custom_annotation.yml:20:11:                   Field `type` references
                                                                          unknown identifier `org.w3id.cwl.cwl.File`,
                                                                          tried
                                                                          file:///Users/brian/Bolton/UKBB/analysis-workflows/definitions_v1.1/types/vep_custom_annotation.yml#vep_custom_annotation/annotation/org.w3id.cwl.cwl.File,
```
The line is under `type: File` below
```
  annotation:
    type:
      type: record
      name: info
      fields:
        file:
          type: File
          label: 'File to be used for annotation, include index file'
```
However when I run cwl-runner validate on the vep.cwl tool itself it works

**Comment by tetron** [comment]
So if I understand correctly, before upgrading, it validates correctly, but the upgraded version fails to validate?

There were some recent changes in the behavior of schema-salad, and cwl-upgrader has an unpinned dependency on schema salad, so that seems related.

Is this part of a SchemaDefRequirement?

**Comment by BJWiley233** [comment]
Yes it is! under `vep.cwl` tool:
```
requirements:
- class: InlineJavascriptRequirement
- class: SchemaDefRequirement
  types:
  - $import: ../types/vep_custom_annotation.yml
```
