### ISSUE TITLE
long form arrays aren't being converted correctly

### ISSUE THREAD

**Issue by jorvis** [common-workflow-language/cwl-upgrader#8]
The [previous version](https://github.com/jorvis/GALES/blob/cc869204cdb004a7c952900692a97b4edd228e6d/cwl/tools/attributor-prok-cheetah.cwl) of one of my tools worked just fine when in draft three, but I upgraded using the utility without errors and the [new version](https://github.com/jorvis/GALES/blob/master/cwl/tools/attributor-prok-cheetah.cwl) errors with this output:

```
/usr/local/bin/cwl-runner 1.0.20170119234115
Resolved 'E_coli_k12_dh10b.fna.partialer/prok-annotation-cheetah.cwl' to 'file:///home/jorvis/GALES/E_coli_k12_dh10b.fna.partialer/prok-annotation-cheetah.cwl'
Tool definition failed initialization:
Tool definition file:///home/jorvis/GALES/bin/../cwl/tools/attributor-prok-cheetah.cwl failed validation:
cwl/tools/attributor-prok-cheetah.cwl:3:1:   Object `cwl/tools/attributor-prok-cheetah.cwl` is not
                                             valid because
                                               tried `CommandLineTool` but
cwl/tools/attributor-prok-cheetah.cwl:254:1:       the `inputs` field is not valid because
cwl/tools/attributor-prok-cheetah.cwl:266:3:         item is invalid because
cwl/tools/attributor-prok-cheetah.cwl:268:5:           invalid field `items`, expected one
                                                       of: 'label', 'secondaryFiles', 'format',
                                                       'streamable', 'doc', 'id', 'inputBinding',
                                                       'default', 'type'
ERROR: Return code 1 when running the following command: cwl-runner --outdir E_coli_k12_dh10b.fna.partialer E_coli_k12_dh10b.fna.partialer/prok-annotation-cheetah.cwl E_coli
_k12_dh10b.fna.partialer/prok-annotation-cheetah.json
```

**Comment by mr-c** [comment]
Manual workaround:

```
inputs:
  source_gff3: File
  m8_files:
    type:
      type: array
      items: File
  hmm_attribute_lookup_file: File
  config_file:
    type: string
    inputBinding:
      prefix: -c
      separate: true
      position: 1
  hmm_files:
    type:
      type: array
      items: File
  output_format:
    type: string
    inputBinding:
      position: 3
      prefix: -f
      separate: true
  blast_attribute_lookup_file: File
  tmhmm_files:
    type:
      type: array
      items: File
```
or more concisely
```
inputs:
  source_gff3: File
  m8_files: File[]
  hmm_attribute_lookup_file: File
  config_file:
    type: string
    inputBinding:
      prefix: -c
      separate: true
      position: 1
  hmm_files: File[]
  output_format:
    type: string
    inputBinding:
      position: 3
      prefix: -f
      separate: true
  blast_attribute_lookup_file: File
  tmhmm_files: File[]
```
